<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Wibawas-MacBook-Pro.local" name="test.JPTest" tests="2" failures="2" timestamp="13 Mar 2018 02:25:33 GMT" time="19.524" errors="0">
  <testcase name="jobsTest" time="10.249" classname="test.JPTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	/post-an-ad is FAILED !! expected [Post Job Ads | The Jakarta Post Jobs] but found [Post Job Ads | The Jakarta Post Jobs 200 ...TEST]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	/post-an-ad is FAILED !! expected [Post Job Ads | The Jakarta Post Jobs] but found [Post Job Ads | The Jakarta Post Jobs 200 ...TEST]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at test.JPTest.testPage(JPTest.java:108)
	at test.JPTest.jobsTest(JPTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- jobsTest -->
  <testcase name="newsTest" time="9.275" classname="test.JPTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	/post-an-ad is FAILED !! expected [Post Job Ads | The Jakarta Post Jobs] but found [Post Job Ads | The Jakarta Post Jobs 200 ...TEST],
	/life/health is FAILED !! expected [Life - health - The Jakarta Post] but found [Life - health - The Jakarta Post 200 ...TEST]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	/post-an-ad is FAILED !! expected [Post Job Ads | The Jakarta Post Jobs] but found [Post Job Ads | The Jakarta Post Jobs 200 ...TEST],
	/life/health is FAILED !! expected [Life - health - The Jakarta Post] but found [Life - health - The Jakarta Post 200 ...TEST]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at test.JPTest.testPage(JPTest.java:108)
	at test.JPTest.newsTest(JPTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- newsTest -->
</testsuite> <!-- test.JPTest -->
